[project]
name = "hexlet-code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
dependencies = [
 "flask",
 "gunicorn", 
 "psycopg2-binary>=2.9.6",
 "python-dotenv",
  "validators"
 ]
