[project]
name = "hexlet-code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8,<4.0"
dependencies = [
  "flask",
  "gunicorn",
  "psycopg2-binary>=2.9.6",
  "python-dotenv",
  "validators",
  "requests",
  "beautifulsoup4"
]

